name: Deploy using AWS SSM Send-Command 

on: [push]

jobs:
    start:
        runs-on: ubuntu-latest 

        steps:
            - uses: actions/checkout@v2

            - name: send-command
              run: |
                ./cicd/deploy.sh

              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_DEFAULT_REGION: 'eu-central-1'
                INSTANCE_ID: ${{ secrets.INSTANCE_ID }}