name: Deploy using AWS SSM Send-Command 

on: [push]

jobs:
    start:
        runs-on: ubuntu-latest 

        steps:
            - uses: actions/checkout@v2

            - name: send-command
              run: |
                cmdid=$(aws ssm send-command \
                    --document-name "AWS-RunShellScript" \
                    --targets "Key=InstanceIds,Values=${{ secrets.INSTANCE_ID }}" \
                    --cli-input-json file://./cicd/deploy.json \
                    --query "Command.CommandId" \
                    --output text)

                echo "$cmdid"

              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_DEFAULT_REGION: 'eu-central-1'

            # - name: AWS SSM Send Command
            #   uses: peterkimzz/aws-ssm-send-command@1.0.1
            #   with:
            #       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID  }}
            #       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY  }}
            #       aws-region: eu-central-1
            #       instance-ids: ${{ secrets.INSTANCE_ID  }}
            #       comment: Deploy the master branch
            #       working-directory: /home/ubuntu/chatapp
            #       command: /bin/sh ./deploy.sh
            
            # Catch SSM outputs
            # - name: Get the outputs
            #   run: echo "The Command id is ${{ steps.ssm.outputs.command-id }}"
